### PR TITLE
Switch exercises to server side composition

### PR DESCRIPTION
**Pull request by mauroservienti**
This PR will be the umbrella PR keeping track of all the work related to switching exercises to Server Side Composition using the Composition API Gateway

* [x] @mauroservienti - Exercise 1, PR ~#198~ https://github.com/Particular/Workshop/pull/207
* [x] @mauroservienti - Exercise 2, PR #199 
* [x] @MarcinHoppe - Exercise 3, PR #200 
* [x] @mauroservienti - Exercise 4, PR #195
* [x] ~update instructions to include .NET Core dependency~ upgrade the projects to .NET Core 2.0 (already part of prerequisites via the ASP.NET and web development workflow)

### CODE REVIEW

**Comment by mauroservienti** [comment]
@MarcinHoppe if you want to have a look this is what's required to migrate exercises to Server Side composition, all commits for far that starts with `4-after:` need to be "applied" adjusting them to all solutions.

What about we sync on this tomorrow morning and decide ho to split the work?

**Comment by mauroservienti** [comment]
@Particular/microservices-workshop-maintainers is it worth sharing the API Gateway code between exercises and demos so to have it in one single place only? This PR we'll make sure it's shared between all exercises but the one used by demos is still a duplicate of this.

**Comment by adamralph** [comment]
@mauroservienti @MarcinHoppe is there going to be a nasty conflict between this and https://github.com/Particular/Workshop/pull/173 ?

**Comment by mauroservienti** [comment]
you bet @adamralph 😄 it this is a race we'll merge first 😉 
On a serious note: what's the status of #173? is it going to be ready on time for next edition? If the answer is no it's probably better to #173 on hold and revisit once this is merged.

One other option (I don't like much) is to "cherry pick" from #173 into sub-PRs here

**Comment by adamralph** [comment]
@mauroservienti the aim is to get both this PR and #173 in before NDC London. They are the two priority items based on feedback. #173 has stalled a bit but I'm intending to pick it up ASAP and get it finished off, however, this PR currently has more momentum so I believe we should aim to get this in first and rebase #173 afterwards.

**Comment by mauroservienti** [comment]
Ok. I should be able to get exercise 1 done by Monday evening, all others are ready for review.

As a note for reviewers: Marcin and myself concentrated on moving composition server side only. There’s a lot of space for server side code cleanup that was not our focus.

**Comment by adamralph** [comment]
@MarcinHoppe @mauroservienti would you recommend a specific order in which the PR's should be reviewed, or does it not make any difference?

**Comment by mauroservienti** [comment]
it doesn't really make a difference @adamralph, we can say that changes applied to exercise 4, 3 and 2 are basically exactly the same changes applied to different folders. Exercise 1 is the one that changed a lot due to changes affecting the UI portion of the exercise and thus documentation as well; not to mention that we changed also the way data are persisted in exercise 1 moving in memory to LocalDB so that all exercises are aligned.

**Comment by mauroservienti** [comment]
this has conflicts with `master` now I'll rebase and force push.

**Comment by mauroservienti** [comment]
Squashed locally, re-testing all exercises before force pushing.

**Comment by mauroservienti** [comment]
@Particular/workshop-maintainers all exercises tested. This is ready for final review (and squash before merge).

**Comment by adamralph** [comment]
@mauroservienti BTW - I also ran the ex 4 after solution as a smoke test, after upgrading to .NET Core 2.0, and all was fine.

**Comment by mauroservienti** [comment]
Run a quick review (from phone) and all look good. I don’t think I’ll be able to perform the squash before beginning next week, feel free to squash them all and merge.

**Comment by mauroservienti** [comment]
:tada:

**Comment by MarcinHoppe** [comment]
:rada:

**Pull request merged**
