### PR TITLE
Update exercises to NSB v7

### PR DESCRIPTION
**Pull request by danielmarbach**
Relates to https://github.com/Particular/DeveloperEducation/issues/1437

- ~[ ] Exercise 1~ no NSB referenced
  - [x] smoke tested
  - [x] check readme
- [x] Exercise 2
  - [x] smoke tested
  - [x] check readme
- [x] Exercise 3
  - [x] smoke tested
  - [x] check readme
- [x] Exercise 4
  - [x] smoke tested
  - [x] check readme
- ~[ ] Demos~ no NSB referenced
- [x] Check all readmes for inconsistencies (caused by changes from v6 to v7) if any

### CODE REVIEW

**Comment by danielmarbach** [comment]
Smoke tested Exercise 2 after and before
Will smoke test Ex 3 and Ex 4 soon

**Comment by timbussmann** [comment]
the demo solutions don't seem to reference any NServiceBus package.

**Comment by timbussmann** [comment]
smoke tested exercise 3. The solutions works fine but I noticed that the licensing path code isn't correct. I suspect the other examples being affected by this as well and will add a task for fix this as I won't get to this today.

**Comment by timbussmann** [comment]
tested all samples. I decided to fix the licensing stuff in a dedicated PR as this would add a lot of noise to this PR.

@Particular/workshop-maintainers please review and merge

**Comment by dvdstelt** [comment]
Please wait with the merge until after SELA :-)

**Comment by danielmarbach** [comment]
SELA is done. It can be merged

**Comment by dvdstelt** [comment]
On Monday I'll do a scan if everything is still working. If it does, I'll merge it immediately.

**Comment by timbussmann** [comment]
ping @dvdstelt

**Comment by adamralph** [comment]
Note that this PR introduced some inconsistencies between the before and after solutions. I've fixed them in https://github.com/Particular/Workshop/pull/277

**Pull request merged**
