### PR TITLE
[WIP] Ignore .vs folders

### PR DESCRIPTION
**Pull request by mauroservienti**

### CODE REVIEW

**Comment by mauroservienti** [comment]
Can be replaced by https://github.com/Particular/Workshop/pull/252

**Comment by dvdstelt** [comment]
Personal question: Why would we want a minimalistic .gitignore file? Is there any benefit?

Devil's Advocate: There should be an issue for this, but there is none. Not even a description?

**Comment by mauroservienti** [comment]
This PR is not about a minimalistic gitignore file, this PR simply adds something that is missing. A minimalistic gitignore file probability would have fixed this long before. If it is stripped down to the minimum required it’s easier to spot things that are missing.

I’m prepping for a workshop on site, and I’m raising PRs as I face issues.

**Comment by dvdstelt** [comment]
I made the comment on the incorrect PR, I will repeat it there. Sorry.

**Comment by mauroservienti** [comment]
No worries 😄

**Comment by mauroservienti** [comment]
Closing in favor of #252

**Pull request closed without merging**
